import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { cookieToInitialState } from "wagmi";
import { headers } from "next/headers";

import { getConfig } from "./config";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SkillSarthi ++",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get("cookie")
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>
          <div>
            <Toaster />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
